---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Day 1: Introduction and Ethics

## Pre-arrival 

- Materiais disponíveis em: https://sicss.io/curriculum

### Introduction to Computational Social Science

- O que é Ciência Social Computacional? Resistir a vontade de criar uma definição formal da área de CSC neste momento. 
  - Essa área está mudando rapidamente, então a definição seria diferente em poucos anos. Evitar definir as "fronteiras" de CSC. 
  - CSC também é, de certa forma, um movimento social: as pessoas estão tentando mudar a forma com que algumas pesquisas acontecem. Ser aberto para receber contribuições de diversas pessoas possibilita que a área de conhecimento cresça.
  
- Exemplo de estudo: [Predicting poverty and wealth from mobile phone metadata - 
Joshua Blumenstock, Gabriel Cadamuro, Robert On](https://science.sciencemag.org/content/350/6264/1073/tab-pdf) - Utilizaram dados telefônicos + Survey com uma amostra pequena + ML. Obtiveram resultados similares aos dados sobre demografia e saúde de um outro Survey promovido pelo governo dos EUA, porém 10 vezes mais rápido e 50 vezes mais barato. A Survey que foi usada para comparação costuma ser realizada a cada 5 anos. Considerando que essa forma é mais rápida e muito mais barata, seria possível coletar as informações com mais frequência.

- Aprender com essas grandes fontes de dados é uma das áreas que está crescendo mais rápido em CSC.

- Qual é uma pergunta interessante a fazer? Como coletar as informações para responder essa pergunta? Como fazer estimativas que tenham sentido para as pessoas que tomam decisões (_policy makers_)?

- CSC: 
  - uma combinação de computação e ciências sociais.
  - muitas vezes envolvem questões éticas e de privacidade, que atualmente são consideradas complexas.
  - combina dados "readymade" e "custommade":
    - "Readymade" - mais ilustrativo do estilo usado em ciência de dados. criatividade para utilizar dados que foram criados para um propósito, e dar um novo propósito. Ex do estudo: usaram dados telefônicos, mas o novo propósito foi investigar a pobreza.    
    - "Custommade" - mais ilustrativo do estilo usado em ciências sociais. Os dados foram criados por um propósito e são usados para o mesmo. 
  - Inclui 5 comunidades chaves: ciências sociais, ciência de dados, negócios, tomadores de decisão, "defensores" da privacidade (privacy advocates).
  - CSC - as mudanças estão sendo conduzidas por  mudanças que estão ocorrendo no mundo. O volume de dados criados e armazenados de forma digital tem dobrado a cada dois anos nos últimos anos. Podemos usar a oportunidade de utilizar estes dados, ou podemos ficar para trás.
  - Dados digitais são criados em todos os lugares. Ex: IOT, alexa. 
  - CSC e técnicas digitais - não subtituem outras técnicas e profissionais, e sim complementam outras ferramentas que já existem. Nossos objetivos como pessoas pesquisadoras continuam os mesmos, mas CSC pode nos ajudar a atingir os objetivos mais rápidos.  
  
- Como criar uma comunidade de CSC? 
  - Cientistas de dados e cientistas sociais trabalhando juntas(os), e cada grupo entendendo que tem coisas que podem aprender e também contribuir/ensinar.
  - O que é Ciência de dados? Aprender com os dados.

  - Pessoas de diferentes contextos disciplinares tem percepções diferentes do que é importante ou interessante em termos de pesquisa. Tentar entender as perspectivas disciplinares das outras pessoas!
  

|  Ciência da computação |  Ciência Social | 
|--:|--:|
|  Estuda vários temas |  Estuda temas sociais |
|  Guiado por métodos |  Guiado por questões | 
|  Usa dados já existentes (bases grandes) |  Usa dados coletados (bases pequenas) |
|  Busca prever |  Busca explicar |

Leituras:

- [ ] [Predicting poverty and wealth from mobile phone metadata](https://science.sciencemag.org/content/350/6264/1073/tab-pdf) - Joshua Blumenstock, Gabriel Cadamuro, Robert On

- [ ] [50 years of Data Science](https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1384734) - David Donoho

### Why SICSS?

- Pq a SICSS foi criada? Muitos desafios: seja na área de pesquisa, como na sociedade.
  - Grandes problemas - Existem diversas questões no mundo que necessitavam das ferramentas de CSC para resolvê-las. Ex. COVID-19.
  - É uma área que está crescendo rapidamente (e em várias direções)
  - Precisamos aprender a crescer juntos para conseguir encontrar soluções para os problemas
  - Oportunidades de treinamento de qualidade são raras.
  
  
- Objetivos da SICSS:
  - Oferecer treinamentos de qualidade e atualizados (state-of-the-art training)
  - Desafiar as fronteiras disciplinares: Quanto mais interdisciplinares os times de pesquisa são, maior impacto eles tem.
  - Alcançar uma grande audiência. A diversidade também será importante para o crescimento da CSC.
  - Material open-source: disponibilizar aulas, videos, códigos, e outros materiais de estudo para que todas as pessoas interessadas possam acessar.
  - Ensinar as pessoas que ensinam! Para que as pessoas que participam do SICSS possa ensinar outras pessoas futuramente.

### Ethics: Part 1

- Esse conteúdo é abordado [no livro de referência: Bit by bit](https://www.bitbybitbook.com/en/1st-ed/ethics/). 

- Cientistas sociais computacionais devem se preocupar com ética. Como comunidade, deveríamos construir normas, padrões e valores que compartilhamos, para aumentar a chance de realizar pesquisas importantes e interessantes. Estamos próximos à áreas "cinzas" em termos éticos (*ethical gray areas*).

- Como pessoas pesquisadoras, precisamos explicar bem para outras pessoas como resolvemos um problema.

- 2 abordagens (ambas limitadas!):
  - Rules-based approach: seguir o que o IRB (Institutional Review Board) define (comentário Bia: segundo a explicação dada no video, o IRB me parece com os comitês de ética em pesquisa no Brasil). Regras que foram escritas em outros contextos, está desatualizada e são difíceis de atualizar. Essa abordagem também dificulta explicar as escolhas para outras pessoas. 
  - Ad hoc approach: pensando por si mesmos, na falta dessas regras e de um debate com a comunidade. Isso dificulta a criação de padrões éticos aceitos pela comunidade.

- Temos o poder de coletar e usar informações de pessoas, sem que elas saibam disso e deem o consentimento. Não é claro o que podemos fazer, e as regras mudam lentamente. Nem os experts de privacidade tem consensos sobre esses temas! 


- A abordagem preferida pelo professor é uma abordagem baseada em princípios *Principles-based approach*.  

- Princípios: 
  - Respeito pelas pessoas: as pessoas participantes decidem, e não as pessoas pesquisadoras. Respeitar a autonomia das pessoas participantes. As pessoas precisam ter autonomia para decidir que se querem participar do estudo ou não. Consentimento informado. (Comentário Bia: no nosso caso essa discussão parece que se conecta com a ideia do Termo de Consentimento Livre e Esclarecido)
  - Beneficiência: minimizar o risco para as pessoas participantes, maximizar os benefícios, e decidir se o estudo deve continuar. Foi feito tudo possível para minimizar o risco para as pessoas participantes? As pessoas pesquisadoras responsáveis pelo estudo não constumam ser as pessoas adequadas para avaliar se os riscos e benefícios estão balanceados. Pessoas externas podem ser importantes nessa avaliação!
  - Justiça: distribuição justa dos malefícios e benefícios da pesquisa. Muitas pesquisas foram feitas com grupos/populações vulneráveis, ex: prisioneiros, pessoas que não tiveram acesso à educação, cidadão destituído de direitos, pessoas com deficiênciais mentais, pacientes de hospitais idosos ou debilitados, entre outros. Outra questão é o acesso do grupo de pessoas que participaram da pesquisa terem acesso aos benefícios da pesquisa. 
  - respeito pela lei e pelo interesse público: 1) compliance (seguir as leis), e 2) accountability baseada em transparência (*transparency-based accountability*). 1) Muitas vezes é confuso/tricky seguir as leis, pois algumas coisas não são claras, principalmente em estudos internacionais. 2) Não devemos fazer a pesquisa secretamente, devemos fazer as coisas abertamente e deixar público para as pessoas. Ex: publicar artigos em revistas de acesso aberto.

- Nenhum princípio é mais importante que outro! Esses princípios envolvem tradeoffs.

- Dois frameworks éticos em conflito, e ambos podem ser extremos e levar a consequências perversas:
  - Consequentialism (focus on ends)
  - Deontology (focus on means)
  

### Ethics: Part 2

Aplicar esses princípios pode ser difícil. 4 tópicos principais:

- **Informed consent (consentimento informado)**
  - Senso comum: devemos obter o consentimento informado de todas  as pessoas que participam da pesquisa
  - Exemplo mostrado: a pesquisa que foi mostrada no exemplo não utilizou consentimento informado, porém o argumento foi bem construído (e a pesquisa não seria possível se fosse necessário o consentimento informado). E foi realizado respeitando a lei (e os IRBs)
  - Ideia melhor (saindo do senso comum): a maioria das pesquisas deve usar alguma forma de consentimento.
  - O que está motivando a vontade de realizar o consentimento informado? Respeito pelas pessoas ou beneficiência?
  
- **Entendendo e gerenciando o risco de informação**
   - Um dos maiores riscos na CSC é o risco de informação. Perigos na divulgação/vazamento de informações pessoais pode ser: econômico (ex. causar a demissão), social (ex. constrangimentos), psicológicos (ex. depressão), criminal (ex. prisão por atividades ilegais). 
   - Senso comum: dados podem ser anonimizados, e sabemos quais dados são sensíveis.
   - Exemplo mostrado: foi realizado um processo de *de-identification* (desidentificação), removendo alguns dados da base de dados para que não seja possível identificar as pessoas participantes do estudo, entenderam que os dados foram "anonimizados". Outra equipe, a partir de desses dados "anonimizados", conseguiram identificar participantes da pesquisa, cruzando os dados da pesquisa com dados de votação. Existe riscos ao combinar diferentes bases de dados.
   - Outro exemplo: dados do netflix, onde foi possível "des-anonimizar" e identificar as pessoas na base, e suas preferências/notas dos filmes. Esses dados são sensíveis para algumas pessoas.
   - Ideia melhor (saindo do senso comum): todos os dados são potencialmente identificáveis e todos os dados são potencialmente sensíveis. 
   - Tendo um plano de proteção de dados sólido, a maioria das pesquisas em CSC tem riscos mínimos em termos de informações
 
- Data protection plans - planos de proteção de dados
  - 5 safes (plano de proteção de dados baseado em 5 proteções, por [Desai et al 2016](https://uwe-repository.worktribe.com/output/914745/five-safes-designing-data-access-for-research)):
    - Projetos seguros: projetos com objetivos responsáveis e permitidos eticamente
    - Pessoas seguras: todas as pessoas que tem acesso aos dados tem que ter recebido treinamento apropriado e ter boas intenções.
    - Dados seguros
    - Safe settigns
    - Safe output
    
- **Privacidade**
  - Senso comum: dicotomia do público/privado. Se for privado deve ser protegido, se for público deve ser aberto.
  - Exemplo mostrado: carta enviada para residentes dizendo que iriam publicar no jornal a lista de pessoas que não votaram na eleição.
  - Ideia melhor (saindo do senso comum): integridade do contexto (*contextual integrity*), pensar no fluxo de informação. A ideia chave são "normas de informação relativas ao contexto", pensar em três dimensões: 
    - atores (tema, remetente, destinatário);
    - atributos (tipos de informação);
    - princípios de transmissão (restrições relativas ao fluxo de informação).
    
- **Tomar decisões em face a incertezas**
  - Senso comum: better safe than sorry (princípio da precaução)
  - Exemplo mostrado: Em alguns casos, todas as abordagens oferecem algum tipo de risco: alguém pode ser prejudicado pelo experimento, ou também outra pessoa pode ser prejudicada se o experimento não acontecer.
  - Ideia melhor (saindo do senso comum): não existe abordagem que não apresenta riscos, e não devemos ver as coisas com uma visão limitada (referência: [Sustein 2005](https://psycnet.apa.org/record/2005-05396-000)).
    
Ways forward:
  - Minimal risk standard: tentar nivelar o risco para o nível que as pessoas estão expostas no dia-a-dia. 
  - Power analysis: quão grande o estudo precisa ser? Mesmo os estudos com riscos mínimos oferecem algum risco. Não queremos que os estudos sejam maiores do que precisam ser, e não estamos colocando mais pessoas em risco do que o necessário. 
  - Ethical-response surveys: descrever um estudo que estamos imaginando/planejando fazer, e fazemos uma survey para um publico variado perguntando o que acham do estudo, e quais mudanças eles fariam para melhorar o estudo em termos éticos.
  - Staged trials: se não sabemos o risco, comece pequeno, em etapas, para focar na segurança.  Exemplo dos medicamentos, vacina.
  
  
- Recomendações: 
  - IRB é o mínimo, não o teto. Devemos seguir o que a IRB solicita. Porém podemos pensar além para melhorar o "balanço" ético da pesquisa.
  - Se imagine no lugar de outras pessoas :) se imagine no lugar das pessoas participates do estudo, dos jornalistas, das pessoas da família das participantes, etc.
  - Pense na ética em pesquisa em algo contínuo!
  

- Leituras:

  - [ ] [Desai et al 2016](https://uwe-repository.worktribe.com/output/914745/five-safes-designing-data-access-for-research)


### Ethics Additions and Extensions

Previsão: 08/05
